### ISSUE TITLE
unable to remove SGDBoop windows 10

### ISSUE THREAD

**Issue by eazymo** [SteamGridDB/SGDBoop#28]
Great program but i dont use it anymore.

I am trying to remove SGDBoop from my windows 10 pc. I followed the instruction how to uninstall it, by running CMD as admin but the command line gives me this error:

"C:\WINDOWS\system32>SGDBoop.exe unregister
'SGDBoop.exe' is not recognized as an internal or external command,
operable program or batch file."

**Comment by manos-paterakis** [comment]
You don't "uninstall" SGDBoop in Windows, since there is no installation in the first place. You can unregister the sgdb:// URI protocol though.

The `SGDBoop register` command needs to be run in the same directory as the SGDBoop.exe file. In other words you need to use the `cd sgdboopDirHere` command to change the working directory, or just go to the SGDBoop.exe's folder and Shift+Right-Click -> "Open command window here" and then run the command.

After that, simply delete the SGDBoop.exe file and its accompanying DLL files, to completely remove SGDBoop from your system.

**Comment by mpaterakis** [comment]
You don't "uninstall" SGDBoop in Windows, since there is no installation in the first place. You can unregister the sgdb:// URI protocol though.

The `SGDBoop register` command needs to be run in the same directory as the SGDBoop.exe file. In other words you need to use the `cd sgdboopDirHere` command to change the working directory, or just go to the SGDBoop.exe's folder and Shift+Right-Click -> "Open command window here" and then run the command. Make sure the command window is run with **Administrator** privileges.

After that, simply delete the SGDBoop.exe file and its accompanying DLL files, to completely remove SGDBoop from your system.

**Comment by eazymo** [comment]
thanks! got it working. real novice here.

**Comment by mpaterakis** [comment]
No problem! This issue will be helpful for others having the same experience. ;)
